### ISSUE TITLE
LSP console client app

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#23]
This client app should build on top of the similarly-purposed LocalDb client app, from which common client abstractions should already have been extracted to a namespace under `Rubberduck.Client`.
- [ ] yup, that's done.

---

We need a relatively complex xaml control that can beautifully layout a bunch of nested configuration settings.

We get a [Console] tab for free by reusing the LocalDb client app UI abstractions, and we'll be able to override the `SettingsCommand` with one of our own.

- [ ] Have a console tab, but just reuse console settings from LocalDb client.

Only the LSP-specific parts should remain:

- [ ] Settings user control (display it in a tab after the console tab), to be reused in the add-in client) to configure the many LSP client/server knobs and switches.

---
### Assumptions

- Each application defines its respective `MainWindow`
- The XAML user control for server console GUI apps is shared; implementations only need to supply a configuration tab, but they are free to supply as many as needed.

### Implementation notes

In order to ensure a consistent user experience across the different applications, the shared XAML user control should be the only child control in the `<MainWindow>`; styles and icons should be imported from the appropriate shared resources libraries (.resx and .png under Rubberduck.Resourcee, anything .xaml is under Rubberduck.UI.Xaml).

**Comment by Greedquest** [comment]
After a convo with ChatGPT

> ```python
> import argparse
> import json
> import pathlib
> import sys
> from pygls.client import LanguageClient
> from pygls.protocol import Notification
> from pygls.features import WORKSPACE_DID_CHANGE_CONFIGURATION, TEXT_DOCUMENT_DID_OPEN
> from pygls.types import (
>     ConfigurationItem, ConfigurationParams, DidChangeConfigurationParams,
>     DidOpenTextDocumentParams, Position, TextDocumentIdentifier, TextDocumentItem,
>     WorkspaceEdit
> )
> 
> class RubberduckClient(LanguageClient):
>     def __init__(self, rubberduck_path: str):
>         super().__init__(name='Rubberduck LSP Client')
>         self.rubberduck_path = rubberduck_path
> 
>     def start(self) -> None:
>         self.create_io_connection(self.rubberduck_path)
> 
> def find_symbol_location(client: RubberduckClient, workspace_uri: str, symbol_name: str) -> Position:
>     params = {
>         'query': symbol_name,
>         'workspaceFolders': [{
>             'uri': workspace_uri,
>             'name': 'workspace'
>         }]
>     }
> 
>     locations = client.send_request('workspace/symbol', params)
>     if locations:
>         location = locations[0]
>         return Position(line=location['range']['start']['line'], character=location['range']['start']['character'])
> 
>     return None
> 
> def main():
>     parser = argparse.ArgumentParser(description='Rename identifier in VBA code using Rubberduck LSP')
>     parser.add_argument('workspace', type=pathlib.Path, help='Path to workspace folder')
>     parser.add_argument('old_name', type=str, help='Old identifier name')
>     parser.add_argument('new_name', type=str, help='New identifier name')
>     args = parser.parse_args()
> 
>     # Initialize the client and start the message connection
>     client = RubberduckClient('/path/to/rubberduck.exe')
>     client.start()
> 
>     # Define a workspace configuration to specify the rename options
>     workspace_uri = f"file://{args.workspace}"
>     rename_config = ConfigurationItem(
>         scope_uri=workspace_uri,
>         section='rubberduck',
>         configuration={
>             'rename': {
>                 'presenter': 'false'
>             }
>         }
>     )
> 
>     # Send a workspace/didChangeConfiguration notification to the server to apply the configuration
>     config_params = ConfigurationParams(items=[rename_config])
>     config_notification = Notification(WORKSPACE_DID_CHANGE_CONFIGURATION, config_params)
>     client.send_notification(config_notification)
> 
>     position = find_symbol_location(client, workspace_uri, args.old_name)
>     if not position:
>         print(f"Symbol '{args.old_name}' not found")
>         return
> 
>     # Send a rename request to the server to perform the refactoring
>     rename_params = {
>         'textDocument': {
>             'uri': workspace_uri
>         },
>         'position': position,
>         'newName': args.new_name
>     }
> 
>     response = client.send_request('textDocument/rename', rename_params)
>     workspace_edit = WorkspaceEdit.from_dict(response)
> 
>     for edit in workspace_edit.changes:
>         print(f"File: {edit}")
>         print("Changes:")
>         for change in workspace_edit.changes[edit]:
>             print(f"  Line: {change.range.start.line}, Character: {change.range.start.character} => {change.new_text}")
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> This code will find the fully qualified symbol in all files of the workspace and rename it. The changes will be printed for each affected file. Note that this code assumes the Rubberduck LSP server supports the workspace/symbol method

**Comment by Greedquest** [comment]
Ah nice, I just asked for the fix

> Yes, you're correct. My apologies for the oversight. You should supply the file URI in the `rename_params`. Since the `find_symbol_location` function returns a `Position`, we need to modify it to return the file URI as well. Here's the updated code:
> 
> ```python
> def find_symbol_location(client: RubberduckClient, workspace_uri: str, symbol_name: str):
>     params = {
>         'query': symbol_name,
>         'workspaceFolders': [{
>             'uri': workspace_uri,
>             'name': 'workspace'
>         }]
>     }
> 
>     locations = client.send_request('workspace/symbol', params)
>     if locations:
>         location = locations[0]
>         position = Position(line=location['range']['start']['line'], character=location['range']['start']['character'])
>         file_uri = location['uri']
>         return position, file_uri
> 
>     return None, None
> 
> # ...
> 
> def main():
>     # ...
>     position, file_uri = find_symbol_location(client, workspace_uri, args.old_name)
>     if not position or not file_uri:
>         print(f"Symbol '{args.old_name}' not found")
>         return
> 
>     # Send a rename request to the server to perform the refactoring
>     rename_params = {
>         'textDocument': {
>             'uri': file_uri
>         },
>         'position': position,
>         'newName': args.new_name
>     }
> 
>     response = client.send_request('textDocument/rename', rename_params)
>     workspace_edit = WorkspaceEdit.from_dict(response)
> 
>     # ...
> ```
> 
> Now, the `rename_params` will have the correct file URI. This should allow the LSP server to rename the symbol as expected.

**Comment by Greedquest** [comment]
Oh wait I'm thinking of an LSP client you can run from the command line as opposed to as a VBE addin. E.g. to run a rename action. Is that not what this issue is about it seems to be a command centre?

**Comment by retailcoder** [comment]
This issue should probably be closed, it's under the "cancelled" status in the backlog (my bad!). Indeed the idea was to just make a client desktop application that can connect to the server and receive (and display) the trace output, while exposing handy tools to configure the server - while there's _some_ value in such a client, it's very much not needed at all.

**Comment by Greedquest** [comment]
@retailcoder got it. I knew it was cancelled (assumed "nice to have but not necessary for MVP" was the reason rather than "this is a bad idea") - but felt as it crossed the boundary into language agnostic Territory, I could use python to make an answer. Am I at least right in thinking the RD LSP will be an exe launched with subprocess by the client. Or is it a c# class under the current model, which the client can instantiate using c# maybe. I.e. does the client have to be c# or interface with c# code?

**Comment by retailcoder** [comment]
The add-in client starts an instance of the LSP server executable, and then uses JSON-RPC/LSP messages to communicate with it.
As such any process that can start an executable and send JSON-RPC messages to it can be a client too, without needing to know about any C# or .net; client needs to know the server/pipe name, what methods are exposed (RPC method names are LSP-defined), and what the parameter schema looks like (also LSP-defined).
Referencing Rubberduck.Client (as the add-in client would), adds an abstraction level that uses Rubberduck.RPC shared client/server models, and exposes normal methods to the rest of RD, so that RPC calls in the add-in client read like any other standard method call.
