### ISSUE TITLE
RD3 Filesystem Criteria

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck3#37]
RD3 will operate from a folder hierarchy of exported module files as the 'source of truth' for the VBA code base.  There have been numerous discussions in the Discord 'rubberducking' channel regarding how the RD3 `Filesystem` should work.  This Issue is created in an attempt to capture and collate past and future 'Decisions', 'Open Topics', and 'Use Cases' surfaced during the discussions.

Over time, the hope is that this Issue contains sufficient criteria and Use Cases to help facilitate the initial implementation.

***Edited 3/13/2023.***
- Adds alternative FileSystem design comment 

### Terms/Definitions:  

- `Filesystem Setup`: The interactive process of creating a valid RD3 environment for a new or existing host document 
- `Filesystem Initialization`: Evaluates the Filesystem of the active host document.  
       -- Creates filesystem objects as needed to establish a valid RD3 Filesystem.
- `Filesystem Synchronization`:  The initialization and design-time processes needed to maintain the host document modules consistent with the "./src" file(s) content.
- `Filesystem Host Folder`: The folder containing the host document of interest
- `Filesystem Code Folder`: The folder containing the code files of interest to the LSP.  The `Filesystem Code Folder` and the `Filesystem Host Folder` can be the same folder.

### Decisions:

1. The default `Filesystem Code Folder` name will be "./src" when the `Filesystem Code Folder` is a direct child of the `Filesystem Host Folder`.
2. Provide `Filesystem Setup` View(s) assisting the user to establish a valid RD3 Filesystem for a host document 

### Open Topics:

1. `Filesystem Initialization`: Detection and Handling of duplicate file names encountered in the folder hierarchy.
2. RD3 host document opened on a non-RD3-enabled VBIDE computer
      a. The only _issue_ identified for this topic so far is the potential for losing Folder annotations.  
          - Resolution: Users expecting to do this would need to retain annotations per Use Case I @ 2.b.ii.
3. `Filesystem Setup`: Introduce project-scope settings (and/or `Filesystem Setup` settings?):
     a. Retain RD3 `Filesystem Setup` preferences
     b. Allow user-defined `Filesystem Code Folder` names other than "./src" 

### Use Cases:

***Use Case I: `Filesystem Setup`: User's initial use of RD3 starting from an RD2 project***

     1. RD3 provides `Filesystem Setup` View(s) to .
     2. @Folder annotations are evaluated to generate a folder structure starting at the `Filesystem Code Folder`
          a. Files without an @Folder annotation are saved in the `Filesystem Code Folder`
          b. Filesystem is synchronized to match host document module content
              1) Unresolved - handling of @Folder annotations after the creation of the folder hierarchy:
                   i) Ignore @Folder annotations in the future. (Disable @Folder related inspections?)
                   ii) Auto-update @Folder annotations based on actual file locations in the future.
                   iii) Make i) and ii) a user choice in `Filesystem Setup` settings
     3. Optional(future): Based on choice of implementing #2 above, Prompt user to  remove @Folder annotations 
     4. If Folder options become a `Filesystem Setting` per 2.b.iii above, re-apply/remove Folder annotations when the user toggles the setting ('Maintain Folder Annotations : boolean' ?).

***Use Case II:  `Filesystem Setup`: User's initial use of RD3 starting from multiple RD2 projects stored in the same folder***

	1. Provide `Filesystem Setup` dialog assisting the user to specify/create a valid RD3 Filesystem
	2. Invoke `Filesystem Initialization`

***Use Case III: `Filesystem Initialization`: User opens a host document that has been moved/copied***

	1. Valid RD3 Filesystem is found: Create folders and files accordingly.
	2. Valid RD3 Filesystem is NOT found: Invoke `Filesystem Setup` dialog/process and `Filesystem Initialization`

***Use Case IV: `Filesystem Synchronization` Files and/or file structure manipulated external to RD3***

    1. This Use Case has a better discussion found in Discord.feature-backlog.Workspace Explorer

**Edit History**

***Edited 3/7/2023.***
- Replaces the use of the term `Workspace` with `Filesystem` since `Workspace` has meaning within the context of a LSP
- Proposes new terms `Filesystem Host Folder` and `Filesystem Code Folder`
					
***Edited 3/5/2023 based on input and comments.***
- Adds 'Terms/Definitions' section
- Adds 'Decision' item
- Simplified ***Use Case*** content descriptions

**Comment by retailcoder** [comment]
**Use case I @ 2b.1**: client-side needs to run a file system watcher, and per LSP it should notify the server about changes. Presumably then, server processes a workspace edit and can send document edits to the client, which could conceivably consist in adjusting various affected `@Folder` annotations. The inspections should be decommissioned then, since the annotations would always be in sync.

On the other hand, perhaps it could be configurable: maybe the user doesn't want folder annotations in their code files. In that case then the server would process the changes without notifying the client - or the server could (optionally) automatically remove all folder annotations; the inspections would still be needed for clients that disable file watcher capabilities / full-auto update.

---

**Use case II**: solved by (annoyingly) changing the source files root to `{host document filename}/src`, which makes a project-level root to add e.g. license and readme documents, and other subfolders ...like an eventual `/packages` folder 🤔

Perhaps the best course of action would be to just ask the user what they want, and then do that:

> **Rubberduck3 | Workspace Initialization**
> This project has no workspace. Root folder is currently `'{path}'`; this action will create a `/src` subfolder at:
> - [o] that location
> - [ ] a subfolder named after the host document
> - [ ] another location (browse)
>
> - [x] remember this decision for future projects

**Comment by Greedquest** [comment]
**Use Case II:**

If we have several .xlsms in a folder not in source control but maybe we soon will, what we really want is to have them each in a subfolder for that project:
```
parent/<host doc name>.xlsm  => 
parent/<host doc name>/<host doc name>.xlsm
```

I guess it depends. If the user wants a separate git repo for each host doc then they should definitely move each one into its own sub folder. If they want a git repo containing several docs in it at once, then they want the subfolder renamed most likely.  


I like Matt's proposal; full flexibility with sensible defaults allowed. One addendum. I think the "at that location" option one should save a relative path so you can cut and paste the document around, use it in a git repo etc. It is the default layout. The other two should use an absolute path, this way you can move the host doc inside the project folder and initialise a git repo there and it won't lose track of the correct folder.


Another technique is to detect if we're inside a git repo already and act accordingly
 - If inside a repo, all the .xlsms are under source control so by default make the `/host_doc/src` subfolder for each (well one at a time, when that project is active) ans use a relative path so the repo can be cloned to any location
 - If not inside a repo, maybe the user isn't after source control for everything so use the `/src` approach just for the host doc. Or create a subfolder and use `/host_doc/src` with an absolute path so the host doc can be moved inside the `/host_doc` folder

**Comment by BZngr** [comment]
The prior comments also address 'Open Topics' item 1 since they include disposition of the host document.  It would be either moved or copied to the Workspace's root folder if necessary.

Also, I think we can/should take a more directive tone since the RD3 workspace structure is  non-negotiable AIUI:

`"<host document name>"` requires a Rubberduck Workspace.  Create the Workspace folder at:

1. `'{path}'/<host document name>/` (recommended)
2. `'{path}'`
3. Another location (browse)

Selection 2 should result in an error message if there is already a `/src/` folder in existence at `'{path}'`

Also, it is entirely possible during Workspace Initialization to discover a git repo for a folder that only contains multiple `xlsm` files (no module exports)...then there may be more to consider.  That said, the recommended Workspace option above would be valid.  There just couldn't be a git repo per host document unless the user chooses to discard the original repo and create new repos for each RD3 Workspace...but I think that all falls outside of RD3's responsibilities.

**Comment by Greedquest** [comment]
I'm torn on the default here. What you actually want if you are using source control is IMO either a src folder below:
```
LibFoo
├── .git
├── LibFoo.xlsm
└── src
     ├── VBAProject
     │   ├── file.cls
     │   └── file.bas
     └── FolderName
         ├── file.bas
         └── file.cls
```
or flat:

```
LibFoo
├── .git
├── LibFoo.xlsm
├── VBAProject
│   ├── file.cls
│   └── file.bas
└── FolderName
    ├── file.bas
    └── file.cls
```

indeed my ideal structure for a library/addin would be something like

```
LibFoo
├── .git
├── TestLibFoo.xlsm
├── LibFoo
│   ├── file.cls
│   └── file.bas
├── tests 'Unit tests
│   ├── file.cls
│   └── file.bas
└── testing 'fixtures to enable tests to run
    ├── file.bas
    └── file.cls
```
Although putting that all under ./src wouldn't be too bad.

The point is, none of these have a `./LibFoo/src` which is more nesting than required.

So although `./<host document name>/src` (`. = {hostDoc.parent}`) is a good default because it will always work whether there is one or several projects on the go at once, `./src` is more aligned with what you want to end up with. So maybe that should be the default unless a folder already exists named that, in which case it is still shown as default option but disabled, and the host doc name option is selected instead.

**Comment by mansellan** [comment]
I guess what I envisaged was:

![image](https://user-images.githubusercontent.com/25420409/222994448-abc84ebe-dcd0-48fb-b1d0-b84b3b303f70.png)

that way, the source is right alongside the host doc. For anyone that uses source control, they would just make sure this was all inside a clean directory rather than My Documents, and check that parent directory in. That way, the host document doesn't encroach on RD's export directory.

Having /src is future proofing for when the duck does more than edit VB(A).

**Comment by Greedquest** [comment]
@mansellan Yeah but wouldn't it be nicer to have docs and src one level up, and a `.rdspace.txt` file in there as well. Just imagining looking at the GitHub repo it's important to have as little nesting as possible.

Future proofing against someone else claiming a future `docs` folder that we wanted for RD auto generated markdown documentation is a sensible precaution, but I honestly feel a little too defensive at the expense of current usability, we can cross that bridge if and when we come to it (e.g. with a configurable folder name)

Flat is better than nested

**Comment by BZngr** [comment]
First - I'm really happy (and relieved) to get all this feedback/help sorting out the Filesystem aspect of RD3.  Thanks!

@Greedquest 
1. Your examples convince me that it does not make sense to identify any particular `Workspace Setup` choice as 'recommended'.
2. I've updated the use of "/src" to "./src" 
3. I'm thinking that **Use Case 0** is a version of **Use Case I** in that the only difference between handling a new RD2 workbook and any other new workbook (with or without macros) is the absence of RD folder annotations.
4. How do you highlight the '@' result? 😄 

### A Definition
Given the conversations to date, I'd like to propose a definition of a minimal and valid RD3 Workspace: 

**A valid RD3 Workspace is:**
- A folder with a single host document,   and
- A specified target folder with 0 to n subfolders containing VBA exported code files.

All the scenarios with or without `git` source control seem to fit in this definition.  Thoughts? 

**Note:** the above definition allows for the possibility of putting the target folder _anywhere_ .  Is this a supportable configuration...or too much 'rope'?

### RD3 Workspaces with existing `git` Source Control 
Common amongst all examples (where `git` source control pre-exists), is that a `.git` file is found in the _same_ folder as the host document.  And, when this condition is found, RD3 _can/should_ accept the target folder/file structure it finds (by discovery).

```
{Parent}
  |-- LibFoo
           |--.git
           |--LibFoo.xlsm
           |--exports (RD3 inferred target folder for import/export)
                    |--file.cls
                    |--file.bas
```	   
and

```
{Parent}
  |-- LibFoo (RD3 inferred target folder for import/export)
           |--.git
           |--LibFoo.xlsm
           |--file.cls
           |--file.bas
```	   
Since a `.git` folder is found in the same folder as `LibFoo.xlsm`, RD3 can sort out the configuration.  RD3 can be confident that it is working with the 'source of truth' without needing to ask the user for any information regarding the `Workspace Setup` and `Workspace Initialization` processes.

Despite RD3 having to figure out how all the exported files are arranged, the 'git-source-control-exists' scenario is the most straightforward IMO. 

However, RD3 could be presented with something like...
```
{Parent}
  |-- FooProject 
           |--.git
           |     |-- Doc
           |           |--Foo.xlsm
           |     |--Code
           |           |--file.cls
           |           |--file.bas
           |-- .gititnore
           |-- etc.
```	
Since `.git` is not in the same folder containing the host document, RD3 will need go through a  `Workspace Setup` and `Workspace Initialization` process with help from the user to specify `Code` as the import/export target folder.

Or   
```
{Parent}
  |-- FooProject 
           |--.git
           |--Foo.xlsm
           |--Foo2.xlsm
           |--Foo3.xlsm
           |-- .gititnore
           |-- etc.
```	   
Since more than one host document exists in the same folder containing `.git`, RD3 will need go through a  `Workspace Setup` and `Workspace Initialization` process with help from the user.

**Comment by BZngr** [comment]
### RD3 Workspaces WITHOUT existing `git` Source Control
 
For all scenarios where a `.git` file is ***NOT*** found in the same folder as the host document, there are far more unknowns.  And, I would expect that the no-git scenario will be the more common scenario.  

The challenge is that _little or nothing_ can be assumed about the state of the files and subfolders when `git` is not involved.  It would seem that the user will need to be provide in some form of Workspace verification every time they open the VBIDE from the host document.

For example:

_Poor Mans Source Control_
```
{Parent}
     |-- Foo
            |--Foo.xlsm (contains a `file.cls` `Class Module`)
            |
            |--LatestVersion
            |     |--Sheet1.doccls
            |	  |--ThisWorkbook.doccls
            |     |--file.cls
            |
            |--Foo_v2020_Demo
                  |--Sheet1.doccls
                  |--ThisWorkbook.doccls
                  |--file.cls
```			 

So, in the absence of a`git` 'seal of approval', only the user can answer the question as to whether `LatestVersion` is, the most current version, and that RD3 should use it as the 'Target Folder'.  If `LatestVersion` is ***not*** the most current state, then the user needs to be helped through the `Workspace Setup` /`Workspace Initialization` process.

Even if we were to persist `LatestVersion` (or `./src`) as a project-scoped setting, it would seem prudent to have the user confirm that the persisted folderpath setting contains the 'source of truth'.

**Comment by BZngr** [comment]
### Proposed alternative RD FileSystem Design/Organization

Most of the discussions/comments to this point have focused on setting up a somewhat prescriptive folder structure surrounding a new or existing host document.  

Alternatively, RD3 can leave the user's working directory largely unchanged.  This can be accomplished by introducing a single new folder (`./.rd`) to the user's working directory.  This single folder contains the virtual file system and (possibly) other settings/meta data supporting RD3.  The `./.rd` can support projects with or _without_ a `Git` folder structure in a consistent manner.

**The `.rd` folder**

1. Much like the `.git` or `.vscode` folders, the `.rd` folder hosts content needed to support the LSP and RDE operations.  
2. The `.rd` folder is placed in same folder as the host document(s) it supports (the _working directory_). 
3. The `.rd` folder can support the presence of 1 to n host documents in the working directory.

The `./.rd` folder has a different purpose than the `./.src` folder discussed previously.  The `./.src` folder was intended to be part of a `Git` or '___Git-ready___' concrete file structure. 

The `./.rd` folder, in contrast, contains VBA code module export files along with the possibility of settings and other data.  The module exports are `LSP`'s virtual file system.  The first time a user opens a host document in RD3, RD3 can independently find or create its virtual file system(s) in the `.\.rd` folder free of any `FileSystem Setup` interactions with the user.

***Resulting Advantages:***
1. RD2 users that open their host documents using RD3 will witness a familiar RD startup process free of any requirement to setup or create a `FileSystem Host Folder` or `FileSystem Code Folder`.
2. RD3 can work with _any_ `Git` folder structure defined by the user...RD3 does not need to define/propose a _default_ or _minimal_ structure.
3. User `Git` workflows applicable to RD2 are also valid for RD3 'out of the box'.
4. RD3 and the `LSP` are supported without making significant structural changes within the user's working directory.
5. Supporting a working directory containing multiple host documents is the same as supporting a working directory containing a single host document.
6. Resolves nearly all the _Use Cases_ and _Open Items_. (And, probably introduces some new ones).

For RD users without a `Git` repository, there is likely _no_ interest in defining or maintaining an on-disk folder hierarchy for VBA exports.  In short, by automatically finding or creating the `.\.rd`  folder, RD3 quietly 'sets up shop'.  And, in the absence of a `Git` repository, the `./.rd`  content is all that is needed support RD3.

For discussion purposes, the folder containing the virtual file system in `.\.rd` will be referred to as `RDRepo`.

***`.\.rd\RDRepo` characteristics:***
1. The `RDRepo` is not _intended_ for direct user interaction.
2. The `RDRepo` folder _name_ can be anything - the host document name, a UUID, etc.
3. The `RDRepo` contains a `working` and a `saved` folder:
      - The `.\.rd\RDRepo\working` folder contains the most recent, potentially unsaved, RDE content
      - The `.\.rd\RDRepo\saved` folder contains...well...saved changes.  The module files in this folder have been, or will be, applied to the host document.
      - The `LSP` and `RDE` _always_ operate on the `.\.rd\RDRepo\working` folder
      - The dual set  of file system folders facilitate detecting, discarding, or keeping changes.
      - The `.\.rd\RDRepo\working` folder allows for retaining unsaved user edits.  e.g., in the case of events like a crash during debugging.
4. In the absence of a `Git` repository, the `.\.rd\RDRepo\` folder structures are defined, initially, by Folder annotations.

### `Git` support

1. Provide the user the choice to setup and operate from a `Git` repository
2. The `.rd\RDRepo\working`  is setup to match the `Git` repository folder structure 
3. `LSP` and `RDE` _always_ operate on the `.rd\RDRepo\working` folder
4.  The `Git` repository folder structure is targeted by `Save` operations rather than the `.rd\RDRepo\saved` folder
5. The `\.rd\RDRepo\saved` folder is deleted. emptied, or ignored when the user chooses to use a folder hierarchy external to the `\.rd` folder.

Notes: 
1. `.rd\RDRepo\working` should probably be added to the `Git` repo's `.gitignore` file to avoid seeing all `.rd\RDRepo\working` updates as changes in `Git`.

**Comment by Greedquest** [comment]
I like that idea (https://github.com/rubberduck-vba/Rubberduck3/issues/37#issuecomment-1466635186) @BZngr 


> The \.rd\RDRepo\saved folder is deleted. emptied, or ignored when the user chooses to use a folder hierarchy external to the \.rd folder.

Yes, and to be more explicit, the user of git should have no idea of the existence of the `.\.rd\RDRepo\saved` folder. We should phrase this as "do you want to setup a sync location for source control" and make no mention of how autosave of RD works behind the scenes.

---

> .rd\RDRepo\working should probably be added to the Git repo's .gitignore file to avoid seeing all .rd\RDRepo\working updates as changes in Git.

I think the user should be expected/ allowed to gitignore the entire `.rd` folder as it is all implementation details in there. It should not be relied upon. It could be marked as a hidden folder.

In future it may even be possible to use a binary format for the working and saved "virtual filesystems" if this makes it faster to load/unload RD projects or easier to use C#'s equivalent to python `pickle` to dump the current working state to a file as serialised object representation rather than actual files. Similar to .twinproj I imagine.

---

> 2. The .rd\RDRepo\working is setup to match the Git repository folder structure

What do you mean exactly? I know what you're getting at, the user should be able to have a src folder in their repo, or keep files at top level, or have named subfolders for each host document/VBProject in the repo. Whatever they like

But practically how does that work? Am I correct in understanding that we request the root folder of an export tree and use that instead of the `saved` folder?

e.g. Initially we have something like this by default before sync-for-source-control is set up: (note the `..` means parent folder)
```
pathTo(saved_dir) = {.\.rd\RDRepo\saved} = Foo.xlsm\..\.rd\RDRepo_Foo\saved
```

But we can point it anywhere we like instead

```
.\.rd\RDRepo_Foo\saved\ => .\ or .\src\ or .\Foo_src\
```

or you could say

```powershell
New-Item -Type SymbolicLink -Path hostDoc\..\.rd\RDRepo_{hostDoc}\saved -Value getRootFolderFromUser()
```

At which point RD places a filesystemwatcher on the "saved" folder (whether it is a folder inside .rd or supplied by the user) and syncs changes into working and into the RDE?

**Comment by BZngr** [comment]
@Greedquest  thanks for the comments/observations.  And, I'm in agreement with them all.

>But practically how does that work? Am I correct in understanding that we request the root folder of an export tree and use that instead of the saved folder?

Yes, that was the approach I was trying to describe.  Once RD knows the root folder of the host document's export tree, RD3 can discover the folder/file structure with which to conform.  And, as you mention, the user's root export folder can be _anywhere_.  We should not assume that the export root folder is, or must be, a peer or child of the host document (though I'm sure that will be the predominant configuration).  I'm fairly certain that keeping `.\.rd\RDRepo\working` in sync with the export tree will be non-trivial.

Regarding my last statement:  I keep finding myself wondering if maintaining a flat file structure in `.\.rd\RDRepo\working`and `.\.rd\RDRepo\saved`  might be advantageous.  So, I might as well try to describe it...

#### Using an `RDRepo` Flat Filesystem hierarchy: 

##### `Git` use case: 
Based on folder data maintained (somewhere) in `.rd`, RD3's filesystem implementation is responsible to transform `.\.rd\RDRepo\working` to and from the user's `git` folder hierarchy.  

##### Non - `Git` use case: 
There is no transformation needed at all.  Only RD3 code module views (e.g., `RD3 Code Explorer`) need to understand the mappings.  The 'mappings' can be 'hard-annotated' folders in the code modules, a persisted version of folder annotations within `./rd`, or a combination of both. 

##### Advantages:
- The `.\.rd\RDRepo\working` and `saved` file _structures_ used by the `RDE` and `LSP` are now immutable.
-  Avoids the complications of mutable folder hierarchies in `.\.rd\RDRepo\`.  The added complexity would be justified if doing so simplified or facilitated `RDE` or `LSP` interactions...but it does not.
- We already have the code to import/export all (or some) files based on a single folder in RD2.
- RD3 uses data about a concrete file system rather than physically synchronizing and replicating it.
