### ISSUE TITLE
View rubberduck.db online

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck3#38]
Hi, Quick issue I will close soon

I'm trying to use this website https://sqliteonline.com/ to view the .db file https://github.com/rubberduck-vba/Rubberduck3/blob/main/Server/Database/Rubberduck.db. I want to know the schema of the db and just view how it is structured. I am able to view the tables but not the Views. The views I guess are higher level structures than the raw tables. If I use 

```
SELECT * From Projects_v1
```

I get an error that the ID column is ambiguous.

Maybe we are not using the same flavour of SQL it expects? Any tips for viewing that file?

**Comment by retailcoder** [comment]
> ErrorCode : 1
Message   : SQL logic error
ambiguous column name: Id
Result    : Error

The script is currently invalid; the ID column is apparently implicitly defined in SQLite. I wasted precious time struggling with the dependencies and getting the RPC server up and figuring out the client side of things... fixing the script is planned under the current sprint, but not started yet.

The model isn't very complex in itself; it's just a matter of getting the SQLite-flavored SQL syntax right to get a valid schema: minor tweaks, but for all tables and views in the schema.

**Comment by retailcoder** [comment]
I haven't tried the online tool, but from my branch I can connect to the .db and send a select query and get ...well the table/column metadata I guess.. seems to work fine. Can't wait for LSP to start requesting records inserted there!

**Comment by Greedquest** [comment]
Nice. Is this a local branch, in your GH fork I'm seeing last change 7 days ago. Yeah will be pretty neat

**Comment by Greedquest** [comment]
Not worth an issue
