### ISSUE TITLE
Persist COM declarations to LocalDb

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#42]
The language server cannot access COM libraries directly from the VBIDE process - the client must send a _command_ to the server, passing it the serialized `ProjectReference` items. The handler for that command can then load the library on the server side and retrieve the declarations: the RD2 code for this should be reusable as-is.

Once the declarations are retrieved, the server should send a `Save` notification to the database server using `IJsonRpcServer`.

- [ ] Implement a LSP server command that receives `ProjectReference` items from the client
  - [ ] Import any missing RD2 code to process COM library references; retrieve the declarations
  - [ ] Use `JsonRpcMethods.Database` method names to notify the database server

**Comment by MDoerner** [comment]
One comment on this, we have two kinds of declarations from COM type libraries in RD2, the ones for referenced libraries and the ones from the hidden user project type libraries.
Persisting the first of the two to the local db probably makes sense. Doing so for the second probably only makes sense for ignored (and possibly locked) projects; the accessible ones will likely be in constant flux.
