### ISSUE TITLE
Fill missing content +RD2 screenshots

### ISSUE THREAD

**Issue by tommy9** [rubberduck-vba/Rubberduck3#57]
## Home / layout / nav

- [x] Top "fixed" header partially scrolls vertically on mobile
- [x] Page partially horizontally scrolls horizontally on mobile
- [x] _Navigation Tools_ image should be more explicit (Version with more features showing: https://user-images.githubusercontent.com/4892984/229369693-be1e341f-428e-4cf2-ba46-f730ca24752e.png)
- [x] Add Ko-fi link
- [x] Add nav link to /About page
- [x] Footer should be as wide as header (full viewport width)
- [x] Breadcrumb should be full-width and not collapse onto itself in smaller displays

## /About

- [x] Markdown page with some history about the project
- [x] Acknowledgements section

## /Features

- [x] Smart Indenter gif is missing
- [ ] Smart Indenter box summary needs another sentence
- [ ] Refactorings box summary is too long
- [x] Navigation tools box summary needs another sentence
- [ ] Annotations box summary needs another sentence
- [ ] Make a card full-width when it's alone in its row?
- [x] ~~Completion gif is too tall~~ (not showing anymore)

### UnitTesting

- [x] Add a table for each type in the fakes API; actually document the feature
- [x] Test Explorer toolwindow page is empty
- [x] Settings page is empty

### Refactorings

- [x] Footer pagination should be aligned with header pagination
- [ ] "New" toggle state isn't obvious enough
- [ ] Requesting new items from a url that doesn't should reset to page 1 (there's no page 2 when there are few new item)
- [x] Items pagination is rendered when the "new" flag is on
- [x] Should have a message that says "no content" or something when there's nothing and pagination is still shown
- [x] Screenshots are too large
- [x] Introduce Field has no content
- [x] Introduce Parameter has no content
- [x] Extract Method needs more content, code block examples
- [x] Move Closer to Usage has no content
- [x] Move Containing Folder has no content
- [x] Move to Folder has no content
- [x] Remove Parameters has no content
- [x] Reorder Parameters has no content

### Navigation Tools

- [x] Code Explorer toolwindow page has no content
- [x] Find all Implementations needs screenshots
- [x] Find all References has no content
- [x] Find Symbol has no content
- [x] To-Do Explorer toolwindow page has no content

### Annotations

- [x] Annotate Menu page has no content
- [ ] Parameters table should be aligned with the "Parameters" heading
- [ ] ExcelHotKeyAnnotation should mention something about only working in Excel?

### Inspections

- [x] Code Metrics toolwindow page needs screenshots
- [x] Inspection Results toolwindow page has no content
- [x] Align items with the headings on the page / remove the weird margins and padding going on there
- [x] Fix layout issues for pagination and filtering (add `col-md-6`)

### Completion

- [x] Self-Closing Pair Completion page needs .gif banners showing it happening
- [x] Smart-Concat Completion page needs a .gif at the bottom

**Comment by retailcoder** [comment]
@tommy9 FYI all the content supplied so far has now been saved into the site's database. The markdown library doesn't appear to natively support tables, so I changed them to plain HTML; also replaced fences with `<code>...</code>` blocks. Looks like there's a bug in the site's backend with the markdown parsing, should probably nest the content in a `<div>` rather than a `<p>`; it's messing up pages with content under a table.
