### ISSUE TITLE
How to new or open a project

### ISSUE THREAD

**Issue by v-jindeng** [rubberduck-vba/Rubberduck3#99]
First, Create %LOCALAPPDATA%\Rubberduck, create \Workspaces and leave empty and copy templates to folder. 
Second, Import RegisterAddIn.reg. 
Then launch app and try to new project. When I click accept button, there is nothing show in app. 
How can I use this program correctly？
![app](https://github.com/user-attachments/assets/8a586ead-bbf5-4895-8e11-0f37afc93b46)

**Comment by retailcoder** [comment]
It isn't currently in a usable state, that's a large part of why there was never any release. In fact it's looking more and more likely that RD3 will realistically leverage an existing editor client like VS Code, at least at first: working on making an editor from scratch is taking limited resources and attention away from the important language server functionality.
